// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snpudvcslyotbulizzbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNucHVkdmNzbHlvdGJ1bGl6emJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzUzNDEsImV4cCI6MjA2MDA1MTM0MX0.T3FT6Fq3xGgL5na7Zfr8wKbTqAxbP5dY6UCSpg-rOio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);